services:
  redis-a:
    image: redis:7-alpine
    container_name: redis-a
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis-a-data:/data

  redis-b:
    image: redis:7-alpine
    container_name: redis-b
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis-b-data:/data

  app-a:
    build: .
    container_name: app-a
    ports:
      - "8080:8080"
    depends_on:
      - redis-a
      - redis-b
    environment:
      REDIS_HOST: redis-a
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      INSTANCE_ID: app-a
      INSTANCE_ROLE: active
      PEER_URL: http://app-b:8080
      REDIS_NODES: redis-a,redis-b,app-a,app-b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app-b:
    build: .
    container_name: app-b
    ports:
      - "8081:8080"
    depends_on:
      - redis-a
      - redis-b
    environment:
      REDIS_HOST: redis-b
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      INSTANCE_ID: app-b
      INSTANCE_ROLE: standby
      PEER_URL: http://app-a:8080
      REDIS_NODES: redis-a,redis-b,app-a,app-b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-a-data:
  redis-b-data:
