port 26379
dir /tmp

sentinel monitor mymaster redis-master 6379 2
sentinel down-after-milliseconds mymaster 1000
sentinel failover-timeout mymaster 3000
sentinel parallel-syncs mymaster 2

sentinel resolve-hostnames yes
sentinel announce-hostnames yes
